import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {createClient} from '@supabase/supabase-js';
import './style.css';

const supabase=createClient(import.meta.env.VITE_SUPABASE_URL||'https://gfvvxwdbahakysxnwyxr.supabase.co',import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY||'sb_publishable_D29Cvfa1ie3-AikSpOOsCg_aL97agYL');
const statuses=[['new','Nouvelle'],['in_progress','En traitement'],['confirmation_pending','Confirmation en attente'],['ready_to_print','Ready to print'],['sent_to_print','Send to print'],['printed','Printed']];
const roleLabels={admin:'Admin',designer:'Designer',print_operator:'Print Operator',staff:'Staff'};
function App(){
 const [session,setSession]=useState(null),[profile,setProfile]=useState(null),[page,setPage]=useState('dashboard'),[orders,setOrders]=useState([]),[customers,setCustomers]=useState([]),[profiles,setProfiles]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);if(data.session)load(data.session.user.id);else setLoading(false)});const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>{setSession(s);if(s)load(s.user.id);else{setProfile(null);setLoading(false)}});return()=>subscription.unsubscribe()},[]);
 async function load(uid){setLoading(true);const [{data:p},{data:o},{data:c},{data:ps}]=await Promise.all([supabase.from('profiles').select('*').eq('id',uid).single(),supabase.from('orders').select('*,customers(full_name,phone),profiles:responsible_id(full_name)').order('created_at',{ascending:false}),supabase.from('customers').select('*').order('created_at',{ascending:false}),supabase.from('profiles').select('*').order('created_at')]);setProfile(p);setOrders(o||[]);setCustomers(c||[]);setProfiles(ps||[]);setLoading(false)}
 if(!session)return <Login onError={setError}/>;if(loading)return <div className="center">Loading…</div>;
 return <div className="app"><header><div className="brand"><b>P</b><span>PRINTLY</span></div><div className="user"><div className="userInfo"><strong>{profile?.full_name}</strong><small>{roleLabels[profile?.role]}</small></div><button onClick={()=>supabase.auth.signOut()}>Déconnexion</button></div></header><nav><button className={page==='dashboard'?'active':''} onClick={()=>setPage('dashboard')}>Dashboard</button><button className={page==='customers'?'active':''} onClick={()=>setPage('customers')}>Clients</button>{profile?.role==='admin'&&<button className={page==='users'?'active':''} onClick={()=>setPage('users')}>Utilisateurs</button>}</nav><main>{error&&<div className="error">{error}</div>}{page==='dashboard'?<Dashboard orders={orders} customers={customers} profiles={profiles} me={profile} reload={()=>load(session.user.id)} setError={setError}/>:page==='customers'?<Customers customers={customers}/>:<Users profiles={profiles} setError={setError} reload={()=>load(session.user.id)}/>}</main></div>
}
function Login({onError}){const[email,setEmail]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false);async function go(e){e.preventDefault();setBusy(true);onError('');const {error}=await supabase.auth.signInWithPassword({email,password});if(error)onError(error.message);setBusy(false)}return <div className="login"><div className="loginCard"><div className="logoBig">P</div><h1>PRINTLY</h1><p>DTF Order Manager</p><form onSubmit={go}><input type="email" placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)} required/><input type="password" placeholder="Mot de passe" value={password} onChange={e=>setPassword(e.target.value)} required/><button disabled={busy}>{busy?'Connexion…':'Se connecter'}</button></form></div></div>}
function Dashboard({orders,customers,profiles,me,reload,setError}){const [open,setOpen]=useState(false),[form,setForm]=useState({name:'',phone:'',title:'',notes:''});const counts=useMemo(()=>Object.fromEntries(statuses.map(([s])=>[s,orders.filter(o=>o.status===s).length])),[orders]);async function create(e){e.preventDefault();setError('');let c=customers.find(x=>x.phone===form.phone.trim());if(!c){const r=await supabase.from('customers').insert({full_name:form.name.trim(),phone:form.phone.trim()}).select().single();if(r.error){setError(r.error.message);return}c=r.data}const r=await supabase.from('orders').insert({customer_id:c.id,title:form.title,responsible_id:me.id,created_by:me.id,notes:form.notes}).select().single();if(r.error){setError(r.error.message);return}setOpen(false);setForm({name:'',phone:'',title:'',notes:''});reload()}async function move(id,status){setError('');const r=await supabase.from('orders').update({status}).eq('id',id);if(r.error)setError(r.error.message);else reload()}return <><div className="top"><div><h2>Commandes</h2><p>{orders.length} commandes • {customers.length} clients</p></div><button className="primary" onClick={()=>setOpen(true)}>+ Nouvelle commande</button></div><div className="stats">{statuses.map(([s,l])=><div className="stat" key={s}><strong>{counts[s]}</strong><span>{l}</span></div>)}</div><div className="kanban">{statuses.map(([s,label])=><section className="column" key={s}><div className="colHead"><b>{label}</b><span>{counts[s]}</span></div>{orders.filter(o=>o.status===s).map(o=><OrderCard key={o.id} o={o} onMove={move}/>)}</section>)}</div>{open&&<div className="modal"><form onSubmit={create} className="modalCard"><div className="modalHead"><h3>Nouvelle commande</h3><button type="button" onClick={()=>setOpen(false)}>×</button></div><input placeholder="Nom du client" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/><input placeholder="Numéro de téléphone" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} required/><input placeholder="Nom de la commande" value={form.title} onChange={e=>setForm({...form,title:e.target.value})} required/><textarea placeholder="Notes" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/><div className="auto">Responsable automatique : <b>{me.full_name}</b></div><button className="primary">Créer la commande</button></form></div>}</>}
function OrderCard({o,onMove}){
 const current=o.status||'new';
 const [menu,setMenu]=useState(false);
 const currentLabel=statuses.find(([value])=>value===current)?.[1]||current;
 async function choose(value){setMenu(false);if(value!==current) await onMove(o.id,value)}
 return <article className="card">
  <div className="cardTop">
   <b>#{o.order_number}</b>
   <span className={'statusBadge '+current}>{currentLabel}</span>
  </div>
  <h3>{o.title}</h3>
  <div className="client">{o.customers?.full_name}<br/><small>{o.customers?.phone}</small></div>
  <div className="responsible">👤 {o.profiles?.full_name||'—'}</div>
  {o.notes&&<div className="notes">{o.notes}</div>}
  <div className="statusChanger">
   <button type="button" className="changeStatusBtn" onClick={()=>setMenu(v=>!v)}>↔ Changer le statut</button>
   {menu&&<div className="statusMenu">
    <div className="statusMenuTitle">Choisir le statut</div>
    {statuses.map(([value,label])=><button type="button" key={value} className={'statusOption '+value+(value===current?' selected':'')} onClick={()=>choose(value)}>
      <span className={'statusDot '+value}></span><span>{label}</span>{value===current&&<span className="check">✓</span>}
    </button>)}
   </div>}
  </div>
 </article>
}
function Customers({customers}){return <div><div className="top"><div><h2>Clients</h2><p>Profils clients enregistrés</p></div></div><div className="grid">{customers.map(c=><div className="customer" key={c.id}><div className="avatar">{c.full_name?.[0]}</div><div><b>{c.full_name}</b><div>{c.phone}</div></div></div>)}</div></div>}
function Users({profiles,setError,reload}){const [f,setF]=useState({full_name:'',email:'',password:'',role:'staff'});const [busy,setBusy]=useState(false);async function add(e){e.preventDefault();setBusy(true);setError('');const {data:{session}}=await supabase.auth.getSession();const r=await fetch(`${import.meta.env.VITE_SUPABASE_URL||'https://gfvvxwdbahakysxnwyxr.supabase.co'}/functions/v1/create-user`,{method:'POST',headers:{Authorization:`Bearer ${session.access_token}`,'Content-Type':'application/json'},body:JSON.stringify(f)});const j=await r.json();if(!r.ok)setError(j.error||'Erreur');else{setF({full_name:'',email:'',password:'',role:'staff'});reload()}setBusy(false)}return <div><div className="top"><div><h2>Utilisateurs</h2><p>Chaque employé possède son propre compte.</p></div></div><div className="userLayout"><form className="modalCard static" onSubmit={add}><h3>Créer un utilisateur</h3><input placeholder="Nom complet" value={f.full_name} onChange={e=>setF({...f,full_name:e.target.value})} required/><input type="email" placeholder="Email" value={f.email} onChange={e=>setF({...f,email:e.target.value})} required/><input type="password" placeholder="Mot de passe" minLength="6" value={f.password} onChange={e=>setF({...f,password:e.target.value})} required/><select value={f.role} onChange={e=>setF({...f,role:e.target.value})}><option value="staff">Staff</option><option value="designer">Designer</option><option value="print_operator">Print Operator</option><option value="admin">Admin</option></select><button className="primary" disabled={busy}>{busy?'Création…':'Créer le compte'}</button></form><div className="userList">{profiles.map(p=><div className="userRow" key={p.id}><div className="avatar">{p.full_name?.[0]}</div><div><b>{p.full_name}</b><small>{roleLabels[p.role]}</small></div></div>)}</div></div></div>}
createRoot(document.getElementById('root')).render(<App/>);
